### ISSUE TITLE
Doesn't work 

### ISSUE THREAD

**Issue by chezadela** [doroved/proxer#1]
macOS 11.7.10 x86

/Users/d/Downloads/proxer_x86_64-apple-darwin_0/proxer ; exit;             
d@MacBook-Pro ~ % /Users/d/Downloads/proxer_x86_64-apple-darwin_0/proxer ; exit;
thread 'main' panicked at src/main.rs:20:50:
Error reading config file: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
zsh: abort      /Users/d/Downloads/proxer_x86_64-apple-darwin_0/proxer
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by doroved** [comment]
@chezadela You need to run the program through a command in the terminal, not by clicking on the file.
```bash
./proxer
```
The proxer.json5 file should be next to proxer

![telegram-cloud-photo-size-2-5474478733139240290-x](https://github.com/user-attachments/assets/e05de582-4975-4059-80ef-d62fb1ab9a07)
